Iter13
dmad1989/urlcut pull request #13
Opened 2024-02-14 14:32 UTC by dmad1989

2024-02-16 16:42 UTC, Perederey requested changes
Хорошая работа, но нужно немного переделать 

1) Context
2) Проверку на ошибки sql
3) Использовать errors.Is / errors.As для ошибок

2024-02-16 16:42 UTC, Perederey commented on cmd/shortener/main.go
> +		}
в go не очень приятно использовать else, попробуй сделать рефакторинг кода (вынести в отдельную функцию или как-то еще), тогда у тебя будет меньше вложений и код будет проще читаться

2024-02-16 16:42 UTC, Perederey commented on cmd/shortener/main.go
> +			panic(err)
может быть log.Fatalf()? Так как через panic можно восстановить приложение?

2024-02-16 16:42 UTC, Perederey commented on internal/cutter/cutter.go
>  package cutter
не совсем понимаю, у тебя cutter - это app получается? но в то же время содержит и store, я бы лучше разделил бы это все

2024-02-16 16:42 UTC, Perederey commented on internal/cutter/cutter.go
> +	UploadBatch(ctx context.Context, batch *jsonobject.Batch) (*jsonobject.Batch, error)
а зачем тут pointer? У тебя же это просто slice?

2024-02-16 16:42 UTC, Perederey commented on internal/dbstore/dbstore.go
> +// todo общее значения для контекста таймаута
попробуй вот так https://pkg.go.dev/embed спрятать sql 

А еще лучше сделать мигратор, например с помощью https://github.com/pressly/goose

2024-02-16 16:42 UTC, Perederey commented on internal/dbstore/dbstore.go
> +	rw sync.RWMutex
mutex - отлично!

2024-02-16 16:42 UTC, Perederey commented on internal/dbstore/dbstore.go
> +	defer cancel()
не уверен, что здесь нужен contex - его обычно передают в транзакциях, а не при создании нового объекта

2024-02-16 16:42 UTC, Perederey commented on internal/dbstore/dbstore.go
> +	return &res, nil
http://go-database-sql.org/errors.html - посмотри вот эту штуку еще, где-то кажется у тебя пропущена проверка на ошибки

2024-02-16 16:42 UTC, Perederey commented on internal/dbstore/dbstore.go
> +		return fmt.Errorf("dbstore.add: write items: %w", err)
все в одном месте тут

лучше разделить логику на repository и application

тут возвращай просто ошибку, а обрабатывай уже на уровне app

2024-02-16 16:42 UTC, Perederey commented on internal/dbstore/dbstore.go
> +	}
так нельзя, надо использовать `errors.Is` / `errors.As`

2024-02-17 11:01 UTC, dmad1989 commented on internal/cutter/cutter.go
>  package cutter
Да, cutter по сути это app. Но он по сути содержит только интерфейс store, который использует для записи и чтения сокращенных значений из базы/файла/мап.
Если я правильно понял принцип многослойной архитектуры должно быть минимум 3 слоя:
api - где описаны хендлеры,
app (в моем случае cutter) - где описана бизнес-логика 
store - где хранятся связи url - сокращение.
При этом api не должен напрямую обращаться к store, поэтому у меня реализованы прокси-методы по типу: 
```
func (a *App) PingDB(ctx context.Context) error {
	return a.storage.Ping(ctx)
}
```
Не много не понимаю, что нужно разделить? 
Реализовать интерфейс store в serverApi, который будет содержать методы для которых не требуется генерация уникального значения?

2024-02-17 11:55 UTC, dmad1989 commented on cmd/shortener/main.go
> +		}
отрефакторил в новый метод

2024-02-17 11:56 UTC, dmad1989 commented on cmd/shortener/main.go
> +			panic(err)
исправил - теперь при любой ошибке при инициализации store мы не сможем восстановить программу

2024-02-17 20:25 UTC, dmad1989 commented on internal/dbstore/dbstore.go
> +// todo общее значения для контекста таймаута
сделал.

2024-02-17 20:27 UTC, dmad1989 commented on internal/dbstore/dbstore.go
> +	defer cancel()
убрал

2024-02-17 20:35 UTC, dmad1989 commented on internal/dbstore/dbstore.go
> +	return &res, nil
вижу. исправил

2024-02-17 21:30 UTC, dmad1989 commented on internal/dbstore/dbstore.go
> +	}
поправил

2024-02-17 21:31 UTC, dmad1989 commented on internal/dbstore/dbstore.go
> +		return fmt.Errorf("dbstore.add: write items: %w", err)
отрефакторил.

2024-02-17 21:52 UTC, dmad1989 commented on internal/cutter/cutter.go
> +	UploadBatch(ctx context.Context, batch *jsonobject.Batch) (*jsonobject.Batch, error)
исправил. 
пока писал код, почему то было ощущение, что если передавать по значению  - не будет записываться сокращения в ответ

2024-02-21 06:15 UTC, merged