Iter15
dmad1989/urlcut pull request #15
Opened 2024-02-26 19:32 UTC by dmad1989

2024-02-29 06:32 UTC, Nikscorp requested changes
оставил комментарии в pr

2024-02-29 06:32 UTC, Nikscorp commented on internal/cutter/cutter.go
> +func (a *App) DeleteUrls(userID string, ids jsonobject.ShortIds) {
то, что здесь написано выглядит очень странным и усложненным.

Все, что тут было нужно, разделить id-шники по батчам (например с помощью fan-in, хотя можно и без этого) и для каждого батча вызывать метод репозитория batch-update.

- batching-а на update-ы нет (проверку на принадлежность юзеру можно тоже сделать батчами)
- проверять принадлежность юзеру не нужно, можно же просто предикат в update добавить
- логика работа с каналом размазана по storage и app слою, следует оставить это только в app
- нет покрытия тестами

2024-02-29 06:32 UTC, Nikscorp commented on internal/dbstore/sql/checkUserURLExists.sql
> +select
проверяй плиз pr перед отправкой, тут GitHub подсвечивает что нет переноса строки в конце файла

2024-03-03 19:15 UTC, dmad1989 commented on internal/cutter/cutter.go
> +func (a *App) DeleteUrls(userID string, ids jsonobject.ShortIds) {
Исправил. Убрал лишние генератор и прочее, теперь расскладываю по батчам в 100 сокращений  и для каждого батча в отдельной горутине делаю update, с учетом автора.
Общение между горутинами сделал через канал, куда передается батч.
Добавил покрытие новой функции тестами: проверяю только утечки горутин, сколько раз вызвали функцию обновление и поведение при ошибке из Strore.

2024-03-03 19:15 UTC, dmad1989 commented on internal/dbstore/sql/checkUserURLExists.sql
> +select
Надеюсь правильно понял замечание - добавил переносы, там где подсвечивал

2024-03-05 08:50 UTC, Nikscorp requested changes
Оставил замечания в комментариях к pr

2024-03-05 08:50 UTC, Nikscorp commented on internal/cutter/cutter.go
> +	bs := 100
лучше сделай это приватной константой имени пакета

2024-03-05 08:50 UTC, Nikscorp commented on internal/cutter/cutter.go
> +	if len(ids) < 100 {
< bs

2024-03-05 08:50 UTC, Nikscorp commented on internal/cutter/cutter.go
> +			go writeBatch(ctx, batchCh)
лучше создать единственную горутину writeBatch, которая будет по range читать из канала и запускать удаление батча.

Как только записал все батчи — закрывай канал и горутина остановится

2024-03-05 08:50 UTC, Nikscorp commented on internal/cutter/cutter.go
> +			batch = batch[:0]
batch продолжает использовать тот же underlying массив, в котором при append-е будут меняться данные. Получается одна горутина меняет 1 массив, а другая его же читает — это. data race => этот кейс не покрыт тестом и/или ты запускаешь тесты без рейс-детектора

2024-03-05 08:50 UTC, Nikscorp commented on internal/cutter/cutter.go
> +	go func() {
если вызов был сделан неблокирующим из хэндлера, тут уже вполне он может быть блокирующим — это будет лучше для тестирования, поэтому wg.Wait() лучше делать в той же горутине, иначе в нем особо нет смысла

2024-03-05 08:50 UTC, Nikscorp commented on internal/dbstore/dbstore.go
> +	s.rw.Lock()
а вот это я раньше просмотрел — и это выглядит очень серьезной проблемой.

Зачем ты используешь мьютексы? У тебя же полноценная субд, всю синхронизацию должна разруливать она, а не ты. Представь, что у тебя запущен не 1 инстанс приложения, а 100 и все они работают на разных серверах, никаких мьютексов в репозитории никогда быть не должно

2024-03-06 20:02 UTC, dmad1989 commented on internal/cutter/cutter.go
> +			batch = batch[:0]
Согласен, реализовал с ошибкой. Запускал тесты с рейс детекором - он ошибок не выявил. Как такой кейс можно покрыть в тесте?

2024-03-06 20:13 UTC, dmad1989 commented on internal/cutter/cutter.go
> +	if len(ids) < 100 {
исправил

2024-03-06 20:13 UTC, dmad1989 commented on internal/cutter/cutter.go
> +	bs := 100
исправил

2024-03-06 21:51 UTC, dmad1989 commented on internal/cutter/cutter.go
> +	go func() {
Убрал

2024-03-06 21:51 UTC, dmad1989 commented on internal/cutter/cutter.go
> +			go writeBatch(ctx, batchCh)
переделал согласно комментарию

2024-03-06 21:53 UTC, dmad1989 commented on internal/cutter/cutter.go
> +			batch = batch[:0]
Переделал: цикл этот убрал вообще, беру сразу входящий срез и по нему "иду", где шаг - размер батча

2024-03-11 02:06 UTC, Nikscorp approved these changes
Часть замечаний осталась, но в целом готов поставить аппрув, задание принято

2024-03-11 02:06 UTC, Nikscorp commented on internal/dbstore/dbstore.go
> +		if _, err = stmt.ExecContext(ctx, id, userID); err != nil && !errors.Is(err, sql.ErrNoRows) {
это все же должен быть один запрос, а не цикл, а так — это никакая не батчевая обработка

2024-03-11 02:06 UTC, Nikscorp commented on internal/cutter/cutter.go
> +func (a *App) DeleteUrls(userID string, ids jsonobject.ShortIds) {
> для каждого батча в отдельной горутине делаю update

ты делаешь не так

2024-04-14 20:54 UTC, merged