Iter5
dmad1989/urlcut pull request #5
Opened 2024-01-13 20:06 UTC by dmad1989

2024-01-15 22:26 UTC, Nikscorp requested changes
Привет!

Неплохая работа, мне понравилась организация кода и лаконичность большинства пакетов.

Ключевые замечания:
- местами очень неудачный нейминг
- переусложненный пакет с пирсингом флагов

Другие замечания указаны в ишью. Прошу исправить.

2024-01-15 22:26 UTC, Nikscorp commented on internal/config/config.go
> +type netAddress struct {
весь этот пакет выглядит переусложненным. Зачем тут например хост и порт отдельно?)
Зачем имплементировать интерфейс Value?

Достаточно ведь просто двух `flag.String` и одного `flag.Parse` и проверить переменные окружения.

Зависимость "github.com/caarlos0/env/v6" тут тоже явно лишняя

2024-01-15 22:26 UTC, Nikscorp commented on internal/cutter/cutter.go
> +type storage struct {
странное название — это скорее service / app или тот же cutter. Слой хранения у тебя как раз ниже.

Также неясно почему эта структура приватная, ты же ее возвращаешь

2024-01-15 22:26 UTC, Nikscorp commented on internal/cutter/cutter.go
> +func (store *storage) Cut(body []byte) (generated string, err error) {
cutter ничего не должен знать не про какое body, это размывание зоны ответственности.
Я бы принимал сразу строку с именем url

2024-01-15 22:26 UTC, Nikscorp commented on internal/cutter/cutter.go
> +	if store.urlsMap.Has(strBody) {
не очень хорошая идея размывать это на 2 метода. Если в будущем появиться логика удаления — придется следить за атомарностью этих двух операций. Кажется стоит обойтись одним методом Get, который помимо строки может или ошибку или булев флажок. (Лучше сразу ошибку, тк в будущем тут будет реальная БД)

2024-01-15 22:26 UTC, Nikscorp commented on internal/cutter/cutter.go
> +		return "", err
актуально для всего кода: ошибки всегда стоит врапать. Иначе по ошибке ты не поймешь где она возникла

2024-01-15 22:26 UTC, Nikscorp commented on internal/store/store.go
> +	for key, val := range u {
лучше завести вторую мапу, чтобы не прокручивать все значения

2024-01-15 22:26 UTC, Nikscorp commented on internal/store/store.go
> +	if len(vs) == 0 {
а зачем эта проверка? "" — это единственная строка длины 0

2024-01-15 22:26 UTC, Nikscorp commented on internal/serverapi/serverapi.go
> +type worker interface {
очень неконсистентный нейминг — у тебя одна сущность называется cutter, worker и storage

2024-01-15 22:26 UTC, Nikscorp commented on internal/serverapi/serverapi.go
> +	fmt.Println(config.Conf.URL.String())
снова отладочная печать. Давай или сделаем логирование с помощью пакета log (пока можно не конфигурировать особо) или удалим. fmt.Print* в коде не должно оставаться

2024-01-15 22:26 UTC, Nikscorp commented on internal/serverapi/serverapi.go
> +	if req.Method != http.MethodPost {
метод проверять не нужно, твой роутер уже делает это за тебя

2024-01-15 22:26 UTC, Nikscorp commented on internal/serverapi/serverapi.go
> +	if !strings.Contains(url, "http://") && !strings.Contains(url, "http//") {
а зачем это нужно? http — это не единственная возможная схема url-а, url лучше возвращать так как нам его передали — не стоит ничего добавлять

2024-01-15 22:26 UTC, Nikscorp commented on internal/serverapi/serverapi.go
> +	if req.Method != http.MethodGet {
аналогично

2024-01-15 22:26 UTC, Nikscorp commented on internal/serverapi/serverapi.go
> +	api.mux.MethodNotAllowed(api.errorHandler)
а зачем нужны 2 последние строчки? Вместо более правильных обработчиков — ты добавляешь свой — менее правильный кмк

Или этого требовали тесты?

2024-01-15 22:26 UTC, Nikscorp commented on internal/serverapi/serverapi.go
> +	if len(path) == 0 {
каноничней сравнивать с "", как ты это делаешь несколькими строками ниже

2024-01-15 22:26 UTC, Nikscorp commented on internal/serverapi/serverapi.go
> +	path := chi.URLParam(req, "code")
параметр называется code, а ты его кладешь в переменную path. Кажется `code` плохое имя)

2024-01-15 22:26 UTC, Nikscorp commented on internal/store/store.go
> +type urlMap map[string]string
я бы все же объявил отдельную структуру и добавил туда rwMutex для синхронизации

2024-01-17 19:02 UTC, dmad1989 commented on internal/cutter/cutter.go
> +	if store.urlsMap.Has(strBody) {
не до конца понял про какие 2 метода речь. 
ты имеешь в виду что нужно объединить Cut(url string) и randStringBytes(n int) 
или Cut(url string) и GetKeyByValue(value string)

2024-01-17 19:23 UTC, dmad1989 commented on internal/cutter/cutter.go
> +	if store.urlsMap.Has(strBody) {
Или речь вообще про app.urlsMap.Has(url) ?

2024-01-19 21:07 UTC, dmad1989 commented on internal/serverapi/serverapi.go
> +	api.mux.MethodNotAllowed(api.errorHandler)
Локальные тесты требовали, но не автотесты. Смутило то, что в первом инкременте было условие что на все запросы кроме POST и GET сервис должен отвечать 400 ошибку

2024-01-19 21:12 UTC, dmad1989 commented on internal/store/store.go
> +	for key, val := range u {
надеюсь правильно понял. Вторую мапу для хранения инверсии ключ-значение?

2024-01-22 07:21 UTC, Nikscorp approved these changes
Привет!

Хорошая работа над ошибками!

Задание принимаю и ставлю аппрув, но указанные замечания крайне желательно поправить.
После правок — можно мерджить в мастер, повторно присылать на ревью не нужно (исправления тривиальные).

2024-01-22 07:21 UTC, Nikscorp commented on internal/config/config.go
> +func InitConfig() {
давай заменим InitConfig на ParseConfig возвращающий структуру и избавимся от глобальных переменных на пустом месте

2024-01-22 07:21 UTC, Nikscorp commented on internal/cutter/cutter.go
> +type StoreMap interface {
интерфейс можно сделать приватным и убрать из него слово Map — данный пакет ничего не знает о внутренностях стораджа

2024-01-22 07:21 UTC, Nikscorp commented on internal/cutter/cutter.go
> +	urlsMap StoreMap
соответственно тут urlsMap — тоже неудачное название, давай назовем просто Storage или как-то так

2024-01-22 07:21 UTC, Nikscorp commented on internal/cutter/cutter.go
> +func (app *App) Cut(url string) (generated string, err error) {
обычно тут одну букву оставляют app -> a

2024-01-22 07:21 UTC, Nikscorp commented on internal/cutter/cutter.go
> +	generated, _ = app.urlsMap.Get(url)
почему мы тут игнорируем ошибку?

2024-01-22 07:21 UTC, Nikscorp commented on internal/cutter/cutter.go
> +		return "", fmt.Errorf("error in cut method: %w", err)
в сообщении ошибки слово error всегда лишнее — и так понятно что это ошибка

2024-01-22 07:21 UTC, Nikscorp commented on internal/cutter/cutter.go
> +		return "", fmt.Errorf("error in cut method: %w", err)
поправь плиз везде

2024-01-22 07:21 UTC, Nikscorp commented on internal/cutter/cutter.go
> +	return base64.URLEncoding.EncodeToString(b)[:n], nil
слайсинг (`[:n]`) тут точно нужен?

2024-01-22 07:21 UTC, Nikscorp commented on internal/serverapi/serverapi.go
> +		panic(err)
лучше все же здесь возвращать ошибку, а обрабатывать ее только на самом высоком уровне (в cmd)

2024-01-22 07:21 UTC, Nikscorp commented on internal/store/store.go
> +		urlMap:    make(map[string]string, 2),
тут и ниже указание capacity выглядит лишним

2024-01-22 07:21 UTC, Nikscorp commented on internal/store/store.go
> +	rw        *sync.RWMutex
мьютекс обычно нет смысла держать по указателю, а вот методы стоит делать с pointer receiver `(store *storage)`

2024-01-22 19:31 UTC, merged