Iter9
dmad1989/urlcut pull request #9
Opened 2024-01-29 13:55 UTC by dmad1989

2024-02-05 10:13 UTC, Nikscorp requested changes
Привет, неплохая работа.

Но работа с файлом крайне сомнительная. Без ее исправления поставить аппрув не могу.

2024-02-05 10:13 UTC, Nikscorp commented on internal/serverapi/serverapi.go
> +	logging.Log.Sugar().Infof("Server started at %s", s.config.GetURL())
если ты всегда делаешь Sugar, то кажется лучше хранить сразу SugaredLogger логгер

2024-02-05 10:13 UTC, Nikscorp commented on internal/cutter/cutter.go
> +		return "", fmt.Errorf("Cut: failed to add path: %w", err)
ошибки в go пишутся с маленькой буквы

2024-02-05 10:13 UTC, Nikscorp commented on internal/logging/logging.go
> +		Log.Sugar().Infoln(
логировать лучше в defer-е,чтобы при панике тоже был лог

2024-02-05 10:13 UTC, Nikscorp commented on internal/logging/logging.go
> +			"; method:", method,
весь смысл zap-а в структурированном логировании. То есть разные сущности логировать в разных полях, чтобы по ним потом можно было искать / парсить их. Ты же здесь все в одну строку конкатишь

2024-02-05 10:13 UTC, Nikscorp commented on internal/logging/logging.go
> +func (r *loggingResponseWriter) Write(b []byte) (int, error) {
Write может быть вызван без предварительного WriteHeader. Тогда клиент получит 200, а ты залогируешь 0

2024-02-05 10:13 UTC, Nikscorp commented on internal/myjsons/myjsons.go
> +package myjsons
очень плохое название для пакета

2024-02-05 10:13 UTC, Nikscorp commented on internal/store/store.go
> +	items, err := readItems(s.fileName)
а зачем все вычитывать то каждый раз из файла? Храни все в мапе и при этом дописывай в файл. Каждый раз перечитывать файл, анмарщалить, а потом еще сканить его в памяти — это оверкилл

2024-02-05 10:13 UTC, Nikscorp commented on internal/store/store.go
> +	if err := writeItems(s.fileName, items); err != nil {
при Add в файл можно просто append-ить по одной записи, а опять же не перезаписывать все.

2024-02-07 22:26 UTC, Nikscorp approved these changes
Часть замечаний была проигнорирована.
Никаких комментариев при этом на мои ишью оставлено не было — так делать не хорошо.

Впрочем, основное замечание про работу с файлом исправлено, поэтому работу принимаю.
Но в будущем попрошу так не делать

2024-02-07 22:26 UTC, Nikscorp commented on internal/config/config.go
> +	defer logging.Log.Sync()
а зачем здесь это?

2024-02-07 22:26 UTC, Nikscorp commented on internal/logging/logging.go
> +		Log.Infow("Response",
почему-то комментарий про defer был проигнорирован.

2024-02-07 22:26 UTC, Nikscorp commented on internal/logging/logging.go
> +func (r *loggingResponseWriter) Write(b []byte) (int, error) {
и здесь комментарий про 200-й код был проигнорирован

2024-02-07 22:28 UTC, Nikscorp commented on internal/logging/logging.go
> +func (r *loggingResponseWriter) Write(b []byte) (int, error) {
Окей, увидел что не проигнорирован, но исправлен не совсем корректно. Представь, что WriteHeader кто-то вызовет 2 раза подряд. Советую посмотреть реализацию такого траппера из chi/middleware (или использовать прямо его)

2024-02-08 07:26 UTC, dmad1989 commented on internal/config/config.go
> +	defer logging.Log.Sync()
внизу по коду я добавлял логирование на 47 строке. подумал что это тут уместно

2024-02-08 07:32 UTC, dmad1989 commented on internal/logging/logging.go
> +		Log.Infow("Response",
я разделил логирование: 
на 40й строке логирую отдельно request
на 47й логирую response
defer Log.Sync() добавил в начале метода на 36й строке.

2024-02-09 15:16 UTC, dmad1989 commented on internal/logging/logging.go
> +func (r *loggingResponseWriter) Write(b []byte) (int, error) {
поправил, по аналогии chi/middleware

2024-02-09 15:17 UTC, dmad1989 commented on internal/config/config.go
> +	defer logging.Log.Sync()
убрал как обсуждали (в инкременте 10)

2024-02-09 15:17 UTC, dmad1989 commented on internal/logging/logging.go
> +		Log.Infow("Response",
поправил в инкременте 10

2024-02-09 15:18 UTC, merged